### ISSUE TITLE
Recorded audio stream is just 0,1,-1

### ISSUE THREAD

**Issue by ed1016** [labstreaminglayer/App-AudioCapture#14]
Hi,

I've recorded an audio stream, but when I try to load it in Matlab (or Python) using the load_xdf function, the audio is a random sequence of 0,1,-1. 

Has this happened before? Is it recoverable or is the file fully corrupted? 

Thank you

![image](https://github.com/labstreaminglayer/App-AudioCapture/assets/52956925/4e3c2356-a523-4107-a139-67de3d40f8fc)

**Comment by cboulay** [comment]
I don't think I've seen that before. If you try to visualize the stream in real-time using one of the [viewers](https://labstreaminglayer.readthedocs.io/info/viewers.html), does it look like it has more than 3 values?

**Comment by ed1016** [comment]
I think it was simply not connected to the correct audio channel - my mistake! Thank you for the viewer suggestion, that will definitely help in not doing that again.

Thanks for your help!
