### ISSUE TITLE
Cannot run the exe file

### ISSUE THREAD

**Issue by ihgumilar** [labstreaminglayer/App-AudioCapture#6]
Hi,

I am trying to run the exe file but it just keeps showing me this message (as attached). Could you give some hand please ?

Thanks
Ihshan

![Questions_audio](https://user-images.githubusercontent.com/49016400/76175875-6ebcf780-6213-11ea-987e-98785b9a2453.JPG)

**Comment by cboulay** [comment]
Get vc_redist.x64.exe from here: https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ihgumilar** [comment]
Thanks a lot
